version: '3.5'
services:
    selenium:
        image: selenium/standalone-${BROWSER:-chrome}:${SELENIUM_IMAGE_TAG:-latest}
        shm_size: "2g"
        expose:
            - "4444"

    tests:
        image: kuma-integration-tests:${TEST_IMAGE_TAG:-latest}
        volumes:
            - ./:/app:z
        depends_on:
            - selenium
        user: ${UID:-1000}
        command: >
            sh -c "urlwait &&
            timeout --preserve-status ${TIMEOUT:-10m}
            py.test tests/functional
            --driver Remote
            --host selenium
            --capability browserName ${BROWSER:-chrome}
            --base-url=${BASE_URL:-https://developer.allizom.org}
            --junit-prefix=${BROWSER:-chrome}
            --junit-xml=/app/test_results/functional-${BROWSER:-chrome}.xml
            --reruns=2
            -vv ${PYTEST_OPTS:-}"
        environment:
            - URLWAIT_TIMEOUT=300
            - URLWAIT_VARNAME=SELENIUM_STATUS_URL
            - SELENIUM_STATUS_URL=http://selenium:4444/wd/hub/status
